'use client';

import { useState } from 'react';
import { Camera, ClipboardCheck, Download, MessageCircle, Moon, Users, Zap } from 'lucide-react';
import { completion, getSeries, mean, number, priorities, sectors, type Person } from '@/lib/demo-data';
import { Badge, BarChart, LineChart, Metric, Panel, Progress, Ring } from './ui';

export function Analytics({roster,days,onExport}:{roster:Person[];days:number;onExport:()=>void}) {
  const [chartMode,setChartMode]=useState('Combined');
  const series=chartMode==='App mood'?[{name:'Daily mood · 1–5',color:'#248f87',values:getSeries(roster,days,'mood')}]:chartMode==='Visual signals'?[{name:'Energy',color:'#4d98d1',values:getSeries(roster,days,'energy')},{name:'Interaction',color:'#bd965d',values:getSeries(roster,days,'interaction')}]:[{name:'Wellbeing',color:'#238c84',values:getSeries(roster,days,'wellbeing')},{name:'Energy',color:'#539ddb',values:getSeries(roster,days,'energy')},{name:'Interaction',color:'#c39754',values:getSeries(roster,days,'interaction')}];
  const avgSleep=mean(roster.flatMap(p=>p.history.slice(-days).map(h=>h.sleep)));
  const moods=[{name:'Good / Great',count:roster.filter(p=>['Good','Great'].includes(p.mood)).length,color:'#30978c'},{name:'Okay',count:roster.filter(p=>p.mood==='Okay').length,color:'#77b1d6'},{name:'Low',count:roster.filter(p=>p.mood==='Low').length,color:'#e7b764'},{name:'Very low',count:roster.filter(p=>p.mood==='Very low').length,color:'#d98172'}];
  let current=0;const stops=moods.map(m=>{const start=current;current+=m.count/roster.length*100;return `${m.color} ${start}% ${current}%`;}).join(',');
  return <><div className="metric-grid"><Metric title="Average sleep" value={number(avgSleep,1)} unit="hrs" sub={`Across ${days} days of visual signals`} icon={Moon} tone="blue"/><Metric title="Check-in completion" value={completion(roster,days)} unit="%" sub={`${days}-day app participation`} icon={ClipboardCheck}/><Metric title="Average energy" value={Math.round(mean(roster.map(p=>p.energy)))} unit="/100" sub="Latest visual activity estimate" icon={Zap} tone="amber"/><Metric title="Average interaction" value={Math.round(mean(roster.map(p=>p.interaction)))} unit="/100" sub="Latest visual interaction estimate" icon={Users} tone="violet"/></div>
    <div className="analytics-primary"><Panel title={`${days}-day wellbeing patterns`} subtitle="Compare changes across the selected personnel" action={<div className="segmented" aria-label="Chart signal type">{['Combined','Visual signals','App mood'].map(m=><button key={m} className={chartMode===m?'active':''} aria-pressed={chartMode===m} onClick={()=>setChartMode(m)}>{m}</button>)}</div>}><LineChart series={series} min={chartMode==='App mood'?1:0} max={chartMode==='App mood'?5:100} height={230} label={`${days}-day ${chartMode.toLowerCase()} trend`}/></Panel>
      <Panel title="Priority distribution" subtitle="Latest support labels"><div className="priority-distribution">{priorities.map((priority)=><div key={priority}><div><Badge priority={priority}/><strong>{roster.filter(p=>p.priority===priority).length}<small> personnel</small></strong></div><Progress value={roster.filter(p=>p.priority===priority).length/roster.length*100} color={priority==='Critical'?'#d57869':priority==='High'?'#d49b65':priority==='Watch'?'#dec582':'#76b6a3'}/></div>)}</div><div className="panel-note">Demo labels support human review.</div></Panel></div>
    <div className="analytics-secondary"><Panel title="Sleep patterns" subtitle="Estimated duration · hours" action={<span className="small-stat">{number(avgSleep,1)} <small>hrs avg.</small></span>}><BarChart values={getSeries(roster,days,'sleep')}/></Panel><Panel title="Check-in completion" subtitle={`By sector · past ${days} days`}><div className="sector-completion">{sectors.filter(s=>roster.some(p=>p.sector===s)).map(s=>{const value=completion(roster.filter(p=>p.sector===s),days);return <div key={s}><span>{s}</span><Progress value={value}/><strong>{value}%</strong></div>;})}</div></Panel><Panel title="Latest reported mood" subtitle="From daily app check-ins"><div className="mood-distribution"><div className="mood-donut" style={{background:`conic-gradient(${stops})`}}><div><strong>{roster.length}</strong><span>check-ins</span></div></div><div>{moods.map(m=><p key={m.name}><i style={{background:m.color}}/><span>{m.name}</span><b>{Math.round(m.count/roster.length*100)}%</b></p>)}</div></div></Panel></div>
    <div className="source-panels"><Panel title="Visual model signals" subtitle="Camera-derived demo measures" action={<span className="source-label"><Camera size={14}/>Visual</span>}><div className="source-values"><div><span>Sleep quality</span><strong>{Math.round(mean(roster.map(p=>p.sleepQuality)))}/100</strong></div><div><span>Interaction level</span><strong>{Math.round(mean(roster.map(p=>p.interaction)))}/100</strong></div><div><span>Energy estimate</span><strong>{Math.round(mean(roster.map(p=>p.energy)))}/100</strong></div></div></Panel><Panel title="Phone app signals" subtitle="Broad themes and participation" action={<span className="source-label app"><MessageCircle size={14}/>App</span>}><div className="source-values"><div><span>Chat sessions · last 7 days</span><strong>{roster.reduce((sum,p)=>sum+p.sessions,0)}</strong></div><div><span>Most reported influence</span><strong>{Object.entries(roster.reduce<Record<string,number>>((a,p)=>({...a,[p.influence]:(a[p.influence]||0)+1}),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'}</strong></div><div><span>Check-ins received today</span><strong>{roster.filter(p=>p.checkedInToday).length} of {roster.length}</strong></div></div></Panel></div>
    <div className="analytics-export"><span>All charts reflect the selected sector and demo period.</span><button className="secondary-button" onClick={onExport}><Download size={15}/>Export personnel snapshot</button></div>
  </>;
}
