'use client';

import { useState, useEffect } from 'react';
import { Activity, Camera as CameraIcon, ChevronRight, Eye, EyeOff, Maximize2, Moon, ScanLine, Users, VideoOff, Zap } from 'lucide-react';
import { cameras, people, mean, type Camera } from '@/lib/demo-data';
import { Empty, Panel, Select } from './ui';
import { Dialog } from './dialog';

export function CameraFrame({camera:c,overlays=true,large=false,onOpen}:{camera:Camera;overlays?:boolean;large?:boolean;onOpen?:()=>void}) {
  return <div className={`camera-frame ${large?'large-camera':''}`}><img src={c.image} alt={`Generated CCTV-style scene of fictional Indian service personnel in ${c.name.toLowerCase()}`} width="1672" height="941"/><div className="camera-top"><span><CameraIcon size={12}/>{c.id}</span><span>{c.captured}</span></div>{overlays&&c.boxes.map((b,i)=><span className="detection-box" style={{left:`${b.x}%`,top:`${b.y}%`,width:`${b.w}%`,height:`${b.h}%`}} key={i}>{i===0&&<span>{c.type} · {c.confidence}%</span>}</span>)}<div className="camera-bottom"><span>SIMULATED FOOTAGE</span>{onOpen&&<button aria-label={`Expand ${c.name}`} onClick={onOpen}><Maximize2 size={15}/></button>}</div></div>;
}
export function Monitoring({sector}:{sector:string}) {
  const [type,setType]=useState('All observations');const [overlays,setOverlays]=useState(true);const [expanded,setExpanded]=useState<Camera|null>(null);const [activeId,setActiveId]=useState('CAM-01');
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('camera');if(id&&cameras.some(c=>c.id===id)){setActiveId(id);setExpanded(cameras.find(c=>c.id===id)||null);}},[]);
  const shown=cameras.filter(c=>(sector==='All sectors'||c.sector===sector)&&(type==='All observations'||c.type===type));
  const active=shown.find(c=>c.id===activeId)||shown[0];
  const roster=active?people.filter(p=>active.people.includes(p.id)):[];
  return <><div className="monitor-toolbar"><div className="monitor-tabs"><span className="camera-count"><CameraIcon size={16}/>{shown.length} demo cameras</span><Select label="Observation type" value={type} onChange={setType} options={['All observations','Rest pattern','Interaction','Activity','Energy estimate']}/></div><button className={`secondary-button ${overlays?'overlay-on':''}`} aria-pressed={overlays} onClick={()=>setOverlays(!overlays)}>{overlays?<Eye size={16}/>:<EyeOff size={16}/>}{overlays?'Detection overlays on':'Detection overlays off'}</button></div>
    <div className="monitor-layout"><div className="camera-grid">{shown.map(c=><article key={c.id} className={`camera-card ${active?.id===c.id?'selected':''}`}><div className="camera-card-heading"><div><h2>{c.name}</h2><p>{c.location}</p></div><span className="camera-status">Demo</span></div><CameraFrame camera={c} overlays={overlays} onOpen={()=>setExpanded(c)}/><button className="camera-card-footer" onClick={()=>setActiveId(c.id)} aria-pressed={active?.id===c.id}><span><ScanLine size={14}/>{c.type}</span><span>View signals <ChevronRight size={14}/></span></button></article>)}{!shown.length&&<div className="panel"><Empty title="No camera matches this view" description="Change the sector or observation filter." action={<button className="secondary-button" onClick={()=>setType('All observations')}>Show all observations</button>}/></div>}</div>
      <aside className="monitor-side">{active&&<><Panel title="Observation summary" subtitle={`${active.id} · ${active.name}`}><div className="observation-main"><span className="source-label"><ScanLine size={13}/>{active.type}</span><strong>{active.reading}<small>{active.unit}</small></strong><p>{active.confidence}% simulated confidence</p></div><div className="observation-metrics"><div><Moon size={17}/><span>Average sleep</span><strong>{mean(roster.map(p=>p.sleep)).toFixed(1)}<small> hrs</small></strong></div><div><Users size={17}/><span>Interaction</span><strong>{Math.round(mean(roster.map(p=>p.interaction)))}<small>/100</small></strong></div><div><Zap size={17}/><span>Energy</span><strong>{Math.round(mean(roster.map(p=>p.energy)))}<small>/100</small></strong></div></div><div className="panel-note">Linked demo signals · {roster.length} fictional records</div></Panel><Panel title="Observation log" subtitle="25 Sep 2026 · IST"><div className="observation-log">{shown.map(c=><button key={c.id} className={active.id===c.id?'active':''} onClick={()=>setActiveId(c.id)}><span className="log-dot"/><span><strong>{c.type}</strong><small>{c.id} · {c.name}</small></span><span>{c.captured.split(' · ')[1].replace(' IST','')}</span></button>)}</div></Panel></>}<div className="simulation-note"><VideoOff size={22}/><strong>Simulation environment</strong><p>Generated camp scenes and illustrative detection boxes. No live cameras connected.</p></div></aside></div>
    {expanded&&<Dialog title={`${expanded.id} · ${expanded.name}`} onClose={()=>setExpanded(null)} wide><div className="expanded-camera"><CameraFrame camera={expanded} overlays={overlays} large/><div><span><strong>{expanded.location}</strong><small>{expanded.captured}</small></span><button className="secondary-button" aria-pressed={overlays} onClick={()=>setOverlays(!overlays)}>{overlays?<EyeOff size={15}/>:<Eye size={15}/>} {overlays?'Hide':'Show'} overlays</button></div></div></Dialog>}
  </>;
}
