'use client';

import { useState, useEffect } from 'react';
import { ArrowUpDown, ChevronLeft, ChevronRight, Download, Search, SlidersHorizontal, X } from 'lucide-react';
import { priorities, priorityOrder, type Person } from '@/lib/demo-data';
import { Avatar, Badge, Empty, Select, Sparkline } from './ui';

export function Personnel({roster,openPerson,onExport}:{roster:Person[];openPerson:(p:Person)=>void;onExport:(p:Person[])=>void}) {
  const [query,setQuery]=useState('');const [priority,setPriority]=useState('All priorities');const [sort,setSort]=useState('Name A–Z');const [page,setPage]=useState(0);
  const filtered=roster.filter(p=>(priority==='All priorities'||p.priority===priority)&&`${p.name} ${p.id} ${p.rank} ${p.location}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='Support priority'?priorityOrder[a.priority]-priorityOrder[b.priority]||a.score-b.score:sort==='Wellbeing index'?a.score-b.score:a.name.localeCompare(b.name));
  const pageCount=Math.ceil(filtered.length/8);const safePage=Math.min(page,Math.max(0,pageCount-1));const visible=filtered.slice(safePage*8,safePage*8+8);
  useEffect(()=>setPage(0),[query,priority,sort,roster.length]);
  return <div className="panel database-panel"><div className="database-toolbar"><div><h2>All personnel <span className="count-chip">{roster.length}</span></h2><p>Explore profiles and their latest wellbeing signals.</p></div><button className="secondary-button" onClick={()=>onExport(filtered)} disabled={!filtered.length}><Download size={15}/>Export CSV</button></div>
    <div className="database-filters"><div className="field-search"><Search size={16}/><input aria-label="Search database" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID, rank or location…"/>{query&&<button aria-label="Clear database search" onClick={()=>setQuery('')}><X size={14}/></button>}</div><div className="filter-selects"><SlidersHorizontal size={15}/><Select label="Filter support priority" value={priority} onChange={setPriority} options={['All priorities',...priorities]}/><Select label="Sort personnel" value={sort} onChange={setSort} options={['Name A–Z','Support priority','Wellbeing index']}/></div></div>
    <div className="table-scroll"><table className="personnel-table"><thead><tr><th>Personnel</th><th>Sector / Location</th><th>Wellbeing</th><th>Sleep</th><th>Latest mood</th><th>Priority</th><th><span className="sr-only">View profile</span></th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><button className="table-person" onClick={()=>openPerson(p)}><Avatar person={p}/><span><strong>{p.name}</strong><small>{p.rank} · {p.id}</small></span></button></td><td><span className="table-main">{p.sector}</span><small className="table-sub">{p.location}</small></td><td><div className="table-index"><strong>{p.score}<small>/100</small></strong><Sparkline person={p}/></div></td><td><span className="table-main">{p.sleep.toFixed(1)} <small>hrs</small></span></td><td><span className="table-main">{p.mood}</span><small className="table-sub">{p.checkedInToday?'Today':'Yesterday'} · {p.checkInTime}</small></td><td><Badge priority={p.priority}/></td><td><button className="icon-button" aria-label={`View ${p.name}'s profile`} onClick={()=>openPerson(p)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table></div>
    {!filtered.length&&<Empty action={<button className="secondary-button" onClick={()=>{setQuery('');setPriority('All priorities');}}>Clear search & priority filter</button>}/>}
    <div className="table-pagination"><span>{filtered.length?`${safePage*8+1}–${Math.min((safePage+1)*8,filtered.length)}`:'0'} of {filtered.length} personnel <span className="subtle">· All records are fictional</span></span><div><button className="page-button" aria-label="Previous page" disabled={safePage===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button>{Array.from({length:pageCount},(_,i)=><button key={i} className={`page-button ${i===safePage?'active':''}`} aria-label={`Page ${i+1}`} aria-current={i===safePage?'page':undefined} onClick={()=>setPage(i)}>{i+1}</button>)}<button className="page-button" aria-label="Next page" disabled={safePage>=pageCount-1} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></div>
  </div>;
}
