'use client';

import { useState } from 'react';
import { Activity, CalendarCheck, Camera, Check, ChevronRight, Clock3, Heart, LockKeyhole, MapPin, MessageCircle, Moon, Smartphone, Users, Zap } from 'lucide-react';
import { dateLabel, type Person } from '@/lib/demo-data';
import { Avatar, Badge, Change, LineChart, Panel, Progress } from './ui';
import { Dialog } from './dialog';

export function Profile({person:p,onClose}:{person:Person;onClose:()=>void}) {
  const [tab,setTab]=useState('Overview');const week=p.history.slice(-7);
  const complete=week.filter(d=>d.checkedIn).length;
  return <Dialog title={`Personnel profile · ${p.id}`} onClose={onClose} wide><div className="profile-header"><Avatar person={p} size="xl"/><div><div className="profile-id">{p.rank} · {p.id}</div><h2>{p.name}</h2><p><MapPin size={13}/>{p.sector} · {p.location}</p></div><div className="profile-header-status"><Badge priority={p.priority}/><small>Fictional personnel record</small></div></div>
    <div className="profile-tabs" aria-label="Profile section">{['Overview','Visual signals','App insights'].map(t=><button key={t} className={tab===t?'active':''} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
    <div className="profile-body">
      {tab==='Overview'&&<><div className="profile-overview-top"><div className="profile-score"><Heart size={19}/><span>Illustrative wellbeing index</span><strong>{p.score}<small>/100</small></strong><Change value={p.trend}/><p>Change across the demo week</p></div><div className="profile-summary"><span className="section-kicker">CURRENT SUPPORT CONTEXT</span><h3>{p.emotion} · {p.mood.toLowerCase()} mood</h3><p>{p.summary}</p><div className="reason-tags">{p.reasons.map(r=><span key={r}>{r}</span>)}</div></div></div>
      <div className="profile-section-grid"><Panel title="Wellbeing pattern" subtitle="Last 7 days · illustrative index"><LineChart height={205} min={20} max={100} series={[{name:'Wellbeing',color:'#238c84',values:week.map(h=>({date:h.date,value:h.wellbeing}))}]}/></Panel><Panel title="Daily check-ins" subtitle={`${complete} of 7 days completed`}><div className="checkin-week">{week.map(h=><div key={h.date} className={h.checkedIn?'complete':''}><span>{dateLabel(h.date,true).slice(0,2)}</span><i>{h.checkedIn?<Check size={14}/>:<span>—</span>}</i></div>)}</div><div className="profile-app-stats"><div><span>Latest mood</span><strong>{p.mood}</strong></div><div><span>Main influence</span><strong>{p.influence}</strong></div><div><span>Last check-in</span><strong>{p.checkedInToday?'Today':'Yesterday'} · {p.checkInTime} IST</strong></div></div></Panel></div></>}
      {tab==='Visual signals'&&<><div className="source-explanation"><Camera size={19}/><div><h3>Visual model observations</h3><p>Illustrative estimates of rest, activity and interaction.</p></div><span className="source-label">Simulated</span></div><div className="profile-visual-metrics">{[{label:'Sleep duration',value:p.sleep,unit:'hrs',progress:p.sleep/8*100,icon:Moon},{label:'Sleep quality',value:p.sleepQuality,unit:'/100',progress:p.sleepQuality,icon:Activity},{label:'Energy estimate',value:p.energy,unit:'/100',progress:p.energy,icon:Zap},{label:'Interaction level',value:p.interaction,unit:'/100',progress:p.interaction,icon:Users}].map(m=><div key={m.label}><m.icon size={20}/><span>{m.label}</span><strong>{m.value}<small>{m.unit}</small></strong><Progress value={m.progress}/></div>)}</div><div className="profile-section-grid"><Panel title="Rest pattern" subtitle="Estimated hours over seven days"><LineChart max={9} min={3} height={205} series={[{name:'Sleep duration',color:'#539ddb',values:week.map(h=>({date:h.date,value:h.sleep}))}]}/></Panel><Panel title="Activity & interaction" subtitle="Illustrative 0–100 indices"><LineChart height={205} series={[{name:'Energy',color:'#238c84',values:week.map(h=>({date:h.date,value:h.energy}))},{name:'Interaction',color:'#c39754',values:week.map(h=>({date:h.date,value:h.interaction}))}]}/></Panel></div></>}
      {tab==='App insights'&&<><div className="source-explanation"><Smartphone size={20}/><div><h3>SAMVED app insights</h3><p>Broad feeling labels and voluntary daily check-ins.</p></div><span className="source-label app">Phone app</span></div><div className="app-insight-grid"><div className="feeling-card"><span className="section-kicker">BROAD FEELING SUMMARY</span><h3>{p.emotion}</h3><p>{p.summary}</p><div className="reason-tags">{p.reasons.map(r=><span key={r}>{r}</span>)}</div></div><div className="profile-app-stats app-stats-card"><div><span>Current mood</span><strong>{p.mood}</strong></div><div><span>Main influence</span><strong>{p.influence}</strong></div><div><span>Chat sessions this week</span><strong>{p.sessions}</strong></div><div><span>Average app use</span><strong>{p.minutes} min / day</strong></div><div><span>Daily check-ins</span><strong>{complete} / 7</strong></div></div></div><Panel title="Daily check-in history" subtitle="Self-reported demonstration values"><div className="checkin-history"><table><thead><tr><th>Date</th><th>Completion</th><th>Mood</th><th>Influence</th></tr></thead><tbody>{[...week].reverse().map(h=><tr key={h.date}><td>{dateLabel(h.date)}</td><td>{h.checkedIn?<span className="completion-label"><Check size={13}/>Completed</span>:<span className="muted">Not submitted</span>}</td><td>{h.checkedIn?['Very low','Low','Okay','Good','Great'][h.mood-1]:'—'}</td><td>{h.checkedIn?p.influence:'—'}</td></tr>)}</tbody></table></div></Panel></>}
      <div className="privacy-strip"><LockKeyhole size={17}/><span><strong>Private conversations stay private.</strong> Only broad summaries are available in the admin view.</span></div>
    </div></Dialog>;
}
